<a href="https://colab.research.google.com/github/chaitalijadhao206-star/Python_Session_14/blob/main/Q_10_MiniProject.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [2]:
# Generate marks for 10 students and 5 subjects
marks = np.random.randint(30, 101, (10, 5))
print("Student Marks:",marks)

# Total marks of each student
total = np.sum(marks, axis=1)
print("\nTotal Marks:",total)

# Average marks of each student
average = np.mean(marks, axis=1)
print("\nAverage Marks:",average)

# Student with highest and lowest total marks
print("\nHighest Total Marks Student Index:", np.argmax(total))
print("Lowest Total Marks Student Index:", np.argmin(total))

# Overall class mean and standard deviation
print("\nClass Mean:", np.mean(marks))
print("Class Standard Deviation:", np.std(marks))

# Top 3 students based on total marks
top3 = np.argsort(total)[-3:]

print("\nTop 3 Students Marks:")
print(marks[top3])

# Reshape array (for demonstration)
reshaped = marks.reshape(5, 10)

print("\nReshaped Array (5 x 10):")
print(reshaped)

Student Marks:
[[67 31 69 97 80]
 [74 40 97 39 59]
 [65 92 35 44 55]
 [53 47 41 31 35]
 [91 80 58 59 30]
 [34 51 41 82 31]
 [97 33 39 97 32]
 [81 62 34 45 79]
 [37 70 71 34 38]
 [62 63 53 84 55]]

Total Marks:
[344 309 291 207 318 239 298 301 250 317]

Average Marks:
[68.8 61.8 58.2 41.4 63.6 47.8 59.6 60.2 50.  63.4]

Highest Total Marks Student Index: 0
Lowest Total Marks Student Index: 3

Class Mean: 57.48
Class Standard Deviation: 21.218143179835504

Top 3 Students Marks:
[[62 63 53 84 55]
 [91 80 58 59 30]
 [67 31 69 97 80]]

Reshaped Array (5 x 10):
[[67 31 69 97 80 74 40 97 39 59]
 [65 92 35 44 55 53 47 41 31 35]
 [91 80 58 59 30 34 51 41 82 31]
 [97 33 39 97 32 81 62 34 45 79]
 [37 70 71 34 38 62 63 53 84 55]]
