<a href="https://colab.research.google.com/github/chaitalijadhao206-star/Python_Session_14/blob/main/Q_1_Array_Properties.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
# Create 5x6 random array
arr = np.random.randint(10, 101, (5, 6))
print("Array:",arr)

# Print shape
print("\nShape of the array:", arr.shape)

# Print total elements
print("\nTotal number of elements:", arr.size)

# Print data type
print("\nData type:", arr.dtype)

Array: [[ 60  49  68  29  59  93]
 [ 79  66  62  92  81  20]
 [ 35  24  42  40  26  26]
 [ 95  37  94  23  34  99]
 [ 70 100  36  22  84  96]]

Shape of the array: (5, 6)

Total number of elements: 30

Data type: int64
