<a href="https://colab.research.google.com/github/chaitalijadhao206-star/Python_Session_14/blob/main/Q_3_2D_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
# Create 4x5 random matrix
arr = np.random.randint(20, 81, (4, 5))

print("Matrix:")
print(arr)

# Print minimum value
print("\nMinimum Value:", arr.min())

# Print maximum value
print("\nMaximum Value:", arr.max())

# Print sum
print("\nSum:", arr.sum())

# Print mean
print("\nMean:", arr.mean())

# Print standard deviation
print("\nStandard Deviation:", arr.std())

print()

# Print row-wise sum
print("\nSum of Each Row:")
print(arr.sum(axis=1))

print()

# Print column-wise sum
print("\nSum of Each Column:")
print(arr.sum(axis=0))

Matrix:
[[33 76 28 30 36]
 [62 64 71 75 52]
 [35 25 76 60 67]
 [54 64 56 61 62]]

Minimum Value: 25

Maximum Value: 76

Sum: 1087

Mean: 54.35

Standard Deviation: 16.589981916807503


Sum of Each Row:
[203 324 263 297]


Sum of Each Column:
[184 229 231 226 217]
