<a href="https://colab.research.google.com/github/chaitalijadhao206-star/Python_Session_14/blob/main/Q_4_Reshape.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
# Create 1D array
arr = np.arange(1, 25)

# Reshape into 4x6
arr1 = arr.reshape(4, 6)

# Reshape into 3x8
arr2 = arr.reshape(3, 8)

# Reshape into 2x3x4
arr3 = arr.reshape(2, 3, 4)

# Print original array
print("Original Array:")
print(arr)

print()

# Print 4x6 array
print("4x6 Array:")
print(arr1)
print("Shape:", arr1.shape)

print()

# Print 3x8 array
print("3x8 Array:")
print(arr2)
print("Shape:", arr2.shape)

print()

# Print 3D array
print("2x3x4 Array:")
print(arr3)
print("Shape:", arr3.shape)

Original Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]

4x6 Array:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
Shape: (4, 6)

3x8 Array:
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]
Shape: (3, 8)

2x3x4 Array:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Shape: (2, 3, 4)
