<a href="https://colab.research.google.com/github/chaitalijadhao206-star/Python_Session_14/blob/main/Q_6_Advanced_Indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
# Create 5x5 random matrix
arr = np.random.randint(1, 101, (5, 5))

# Print array
print("Array:")
print(arr)

# Print diagonal elements
print("\nDiagonal Elements:")
print(np.diag(arr))

# Print elements greater than 50
print("\nElements Greater Than 50:")
print(arr[arr > 50])

# Replace elements less than 30 with 0
arr[arr < 30] = 0

# Print modified array
print("\nModified Array:")
print(arr)

Array:
[[12 15 68 26 70]
 [17 36 10 75  1]
 [11 11  7 78 17]
 [25 66  2 47 88]
 [94 30  2  6 12]]

Diagonal Elements:
[12 36  7 47 12]

Elements Greater Than 50:
[68 70 75 78 66 88 94]

Modified Array:
[[ 0  0 68  0 70]
 [ 0 36  0 75  0]
 [ 0  0  0 78  0]
 [ 0 66  0 47 88]
 [94 30  0  0  0]]
