<a href="https://colab.research.google.com/github/chaitalijadhao206-star/Python_Session_14/blob/main/Q_8_Matrix_Mult.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
# Create two 3x3 matrices
A = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

B = np.array([[9, 8, 7],[6, 5, 4],[3, 2, 1]])

# Element-wise multiplication
element = A * B
print("Element-wise Multiplication:",element)

# Matrix multiplication
matrix = A @ B
# matrix = np.dot(A, B)   # You can also use this

print("\nMatrix Multiplication:")
print(matrix)

# Difference:
# *:Multiplies corresponding elements.
# @ or np.dot():Performs actual matrix multiplication.

Element-wise Multiplication: [[ 9 16 21]
 [24 25 24]
 [21 16  9]]

Matrix Multiplication:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
